In [1]:
import pandas as pd
from helpers import perform_weighted_one_hot_encoding

df = pd.read_pickle("../data/cocktail_dataset_v1.pkl")

In [2]:
df = df.join(pd.get_dummies(df["glass"], prefix="glass"))

In [3]:
perform_weighted_one_hot_encoding(df)

C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.2  0.33 0.2 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.0625 0.1875 0.25   0.25   0.25   0.1875 0.1875 0.1875 0.1875]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.125   0.04166]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.25  0.125]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.1875  0.125   0.125   0.125   0.75    0.125   0.125   0.1875  0.09375
 0.25    0.25    0.25    0.3125  0.25    0.1875  0.25    0.09375 0.125  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.33 1.   1.   0.66 0.33]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.25   0.1875 0.1875 0.125  0.0625 0.0625 0.125  0.1875 0.125  0.125
 0.0625]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.125  0.1875 0.0625 0.1875 0.1875 0.1875 0.1875 0.25   0.75   0.0625
 0.0625 0.0625 0.0625 0.0625 0.0625]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.1875  0.0625  0.125   0.125   0.25    0.25    0.1875  0.09375 0.1875
 0.25    0.1875  0.25    0.1875  0.09375 0.09375 0.1875  0.25    0.1875
 0.25    0.25    0.25    0.25    0.25    0.25    0.25    0.1875  0.25
 0.25    0.1875  0.25    0.1875  0.25    0.1875  0.1875  0.2     0.125
 0.20833 0.1875  0.25    0.1875  0.1875  0.1875 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.1875 0.1875 0.1875 0.25   0.25   0.25   0.25   0.3125 0.125  0.1875
 0.1875 0.1875 0.1875 0.25   0.25   0.25   0.0625 0.25  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.125 0.2  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.0625 0.25  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.166 0.166 0.166 0.166]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.166 0.166 0.166 1.    0.166 0.166 0.166]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.1875 1.     0.625  1.    ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.75]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.33]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.5  0.66]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.2]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\timus\kod\Solvro-rekrutacja\helpers\ingredients.py:199: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.33]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)
df_preprocessed = pd.concat([df.iloc[:, 1], df.iloc[:, -32:]], axis=1)

In [5]:
df_preprocessed

                      name  glass_Brandy snifter  glass_Champagne flute  glass_Cocktail glass  glass_Collins glass  glass_Copper Mug  glass_Highball glass  glass_Old-fashioned glass  glass_Pousse cafe glass  glass_Whiskey Glass  glass_Whiskey sour glass  glass_White wine glass  ingredient_water  ingredient_rum  ingredient_fortified_wine  ingredient_syrup  ingredient_spirit  ingredient_bitter  ingredient_vodka  ingredient_liqueur  ingredient_gin  ingredient_whisky  ingredient_soft_drink  ingredient_wine  ingredient_fruit  ingredient_juice  ingredient_egg  ingredient_cream  ingredient_tea  ingredient_salt  ingredient_flower  ingredient_spice  ingredient_sauce
0                   Mojito                 False                  False                 False                False             False                  True                      False                    False                False                     False                   False              0.20          0.3125                    0.00000             1.000             0.0000               0.00            0.0000              0.0000          0.0000             0.0000                   0.00             0.00             1.000               0.0             0.0             0.000             0.0              0.0                0.5           0.00000               0.0
1            Old Fashioned                 False                  False                 False                False             False                 False                       True                    False                False                     False                   False              0.33          0.0000                    0.00000             1.000             0.0000               0.66            0.0000              0.0000          0.0000             0.0825                   0.00             0.00             0.000               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
2          Long Island Tea                 False                  False                 False                False             False                  True                      False                    False                False                     False                   False              0.00          0.0625                    0.00000             0.000             0.0625               0.00            0.0625              0.0000          0.0625             0.0000                   0.33             0.00             0.500               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
3                  Negroni                 False                  False                 False                False             False                 False                       True                    False                False                     False                   False              0.00          0.0000                    0.12500             0.000             0.0000               0.00            0.0000              0.1250          0.1250             0.0000                   0.00             0.00             0.000               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
4             Whiskey Sour                 False                  False                 False                False             False                 False                       True                    False                False                     False                   False              0.00          0.0000                    0.00000             0.250             0.0000               0.00            0.0000              0.0000          0.0000             0.2500                   0.00             0.00             0.166               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
..                     ...                   ...                    ...                   ...                  ...               ...                   ...                        ...                      ...                  ...                       ...                     ...               ...             ...                        ...               ...                ...                ...               ...                 ...             ...                ...                    ...              ...               ...               ...             ...               ...             ...              ...                ...               ...               ...
129  Quarter Deck Cocktail                 False                  False                  True                False             False                 False                      False                    False                False                     False                   False              0.00          0.1875                    0.04166             0.000             0.0000               0.00            0.0000              0.0000          0.0000             0.0000                   0.00             0.00             0.500               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
130              Queen Bee                 False                  False                  True                False             False                 False                      False                    False                False                     False                   False              0.00          0.0000                    0.06250             0.000             0.1250               0.00            0.1875              0.0000          0.0000             0.0000                   0.00             0.00             0.000               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
131        Queen Charlotte                 False                  False                 False                 True             False                 False                      False                    False                False                     False                   False              0.00          0.0000                    0.00000             0.125             0.0000               0.00            0.0000              0.0000          0.0000             0.0000                   0.20             0.25             0.000               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
132        Queen Elizabeth                 False                  False                  True                False             False                 False                      False                    False                False                     False                   False              0.00          0.0000                    0.06250             0.000             0.0000               0.00            0.0000              0.7500          0.1875             0.0000                   0.00             0.00             0.000               0.0             0.0             0.000             0.0              0.0                0.0           0.00000               0.0
133                Quentin                 False                  False                  True                False             False                 False                      False                    False                False                     False                   False              0.00          0.1875                    0.00000             0.000             0.0000               0.00            0.0000              0.0625          0.0000             0.0000                   0.00             0.00             0.000               0.0             0.0             0.125             0.0              0.0                0.0           0.03125               0.0

[134 rows x 33 columns]

In [6]:
df_preprocessed.to_pickle("../data/cocktail_dataset_preprocessed.pkl")